[font]
size = 7

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[colors.primary]
foreground = "#dddddd"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#cc0403"
green = "#19cb00"
yellow = "#cecb00"
blue = "#0d73cc"
magenta = "#cb1ed1"
cyan = "#0dcdcd"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#f2201f"
green = "#23fd00"
yellow = "#fffd00"
blue = "#1a8fff"
magenta = "#fd28ff"
cyan = "#14ffff"
white = "#ffffff"

[cursor]
thickness = 1.0
# 🏹
